apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "distributed-jmeter.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    helm.sh/chart: {{ include "distributed-jmeter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/health/vitals"
        prometheus.io/port: "3040"
    spec:
     containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          limits:
            cpu: 5000m
            memory: 5096Mi
          requests:
            cpu: 4000m
            memory: 4072Mi
          args: ["server"]
          ports:
            - containerPort: 50000
            - containerPort: 1099
