apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "distributed-jmeter.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    helm.sh/chart: {{ include "distributed-jmeter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
spec:
  replicas: {{ .Values.master.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: master
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  {{ include "distributed-jmeter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: master
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/health/vitals"
        prometheus.io/port: "3040"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 1Gi
          args:
            - master
          ports:
            - containerPort: 60000
